### ISSUE TITLE
How to handle future gas prices?

### ISSUE THREAD

**Issue by mudgen** [ETH-Pantheon/Aion#13]
Let's say that someone schedules a transaction to occur one month in the future.

There is no way to know what the gas price is one month in the future.  So how can the gas price be included in the scheduled execution of the transaction?  

It seems very possible a scheduled transaction will either pay too little or too much. Any idea to solve or mitigate this problem?

**Comment by jfdelgad** [comment]
Indeed this is an issue. Unfortunately this will require to have a way to charge the user the extra cost. Assuming the gas price is lower than the estimated at the time of execution, the solution could be to ask the user (smart contract receiving the call) to reimburse the extra cost. 

Another solution is that have an account based service and Aion when executing the transactions takes from the account the cost of the transaction. In a way this is how is done now, but Aion assumes the gasprice idicated is fixed, instead, users can specify what is the maximum that they are willing to pay (maximun gas price) and Aion uses just what the currrent price is at transaction time. 

In the case of the gas amount there is no problem as the user can provide more than enough and the remaining gas is refunded. This can also be used by Aion, for instance, if the user specify an amount of gas and a gas price, but at transaction time the gas price has increased, Aion could reduce the gas amount and increase the gas price. Because th excess of gas is always returned this would work well but requires changes in teh smart contract to allow Aion to change the gas price and gas amount, which are validated in the smart contract.

If you have any ideas, let me know.

**Comment by ETH-Pantheon** [comment]
There is no way to control the gas prices or predict it. One of the main design rules of AION is that none of the parameters set by users can be changed by AION executor. 

An initial solution is to send a message to users when soon to be executed transactions will likely fail due to lower gas price set in the schedule transaction (We are indeed working on this).

In case that the scheduling is made via a smart contract. it is possible to cancel and re-schedule transactions knowing the current gas price through an oracle.
