### ISSUE TITLE
Looping over scheduleTransaction()

### ISSUE THREAD

**Issue by Banksy-said-hi** [ETH-Pantheon/Aion#24]
Hi

I was struggling with looping over the scheduleTransaction() of your first sample contract which tries to send a eth transaction at some specified time or block. 

I have developed a simple loop(for) logic to make multiple synced transactions, however, I am given this error: "the execution failed due to an exception"

Also, I have opened a question in ETHstackexchange. It would be great to have your opinion about this issue.
https://ethereum.stackexchange.com/questions/114413/looping-over-scheduling-eth-transaction

This is my main scheduleTransaction() function
![Uploading Screen Shot 2021-11-27 at 5.24.14 PM.png…]()

And this is my second one, which is connected to the main function. However, it gives an error while getting executed for scheduling multiple transactions.
<img width="639" alt="Screen Shot 2021-11-27 at 5 25 35 PM" src="https://user-images.githubusercontent.com/72816123/143684392-9ef13ede-de5c-435b-98fb-cd7804c54518.png">

**Comment by Banksy-said-hi** [comment]
I assume I have to provide enough gas while calling scheduletransaction(i) in my loop. But I'm not sure how to do it :(

**Comment by jfdelgad** [comment]
Hello Rahim

The example Recurrent transactions is what you need. The code that you are posting is not correct because it sends several request within a single transaction.

The way to get this to work is as in the example. First you schedule the transaction and after the number of blocks you requested, Aion smart contract sends your contract a transaction. This transactions call MyFunction (in the example)  you can put there the code you need to execute (for instance sending ether) and then request another scheduling of a transaction and os on.

Notice that Aion creates an account for you (an smart contract) so you need to ensure that the call to MyFunction comes from that specific smart contract.

**Comment by Banksy-said-hi** [comment]
You are an angel. Thanks
